# OpenTelemetry Collector configuration for LangSmith
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

exporters:
  otlphttp/langsmith:
    endpoint: 'https://api.smith.langchain.com/otel'
    headers:
      'x-api-key': '${env:LANGSMITH_API_KEY}'
      'Langsmith-Project': '${env:LANGSMITH_PROJECT}'

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/langsmith]

  extensions: []